KES Agent prerequisites
IntersectMBO/cardano-base pull request #317
Opened 2022-10-13 14:39 UTC by tdammers

Adds direct serialization/deserialization of KES sign keys.

We need this in order to send keys over network sockets without touching the GHC heap (which would violate mlocking protections).

2023-04-19 13:49 UTC, tdammers commented
This currently depends on #388 and #389; those should be dealt with first before merging this.

2023-10-30 20:56 UTC, lehins requested changes
I'll review more tomorrow. Here is my feedback thus far

2023-10-30 20:56 UTC, lehins commented on cardano-crypto-class/src/Cardano/Crypto/KES/CompactSum.hs
> +      maybe (fail "Invalid hash") return $! VerKeyCompactSumKES <$!> hashFromBytes bs
Why all the strictness? Why extra allocation, why not use `ForeignPtr`?
```suggestion
    fptr <- mallocForeignPtrBytes len
    withForeignPtr fptr $ \ptr -> do
      pull ptr len
      let bs = fromForeignPtr 0 len fptr
      maybe (fail "Invalid hash") (return . VerKeyCompactSumKES) $ hashFromBytes bs
```

We'll need some helpers for ForeignPtrs that work in `MonadST`, but that's totally doable and better than using `allocaBytes` everywhere.

2023-10-31 20:46 UTC, tdammers commented on cardano-crypto-class/src/Cardano/Crypto/Libsodium/Memory/Internal.hs
> +allocaBytes :: (MonadThrow m, MonadST m) => Int -> (Ptr a -> m b) -> m b
Superseded - I have implemented `allocaBytes` in terms of `ForeignPtr` now.

2023-10-31 20:46 UTC, tdammers commented on cardano-crypto-class/src/Cardano/Crypto/Libsodium/Memory/Internal.hs
> +free = unsafeIOToMonadST . Foreign.free
Fixed.

2023-10-31 20:57 UTC, tdammers commented on cardano-crypto-class/src/Cardano/Crypto/Libsodium/Memory/Internal.hs
> +  allocaBytes (len + 1) $ \buf -> do
Removed the nul terminator, as discussed.

2023-10-31 21:12 UTC, tdammers commented on cardano-crypto-class/src/Cardano/Crypto/KES/CompactSum.hs
> +      push (castPtr ptr) (fromIntegral len)
I'd rather avoid the potential foot-gun that is `unsafeUseAsCStringLen`; this isn't performance critical code, so I'm perfectly happy with a little bit of redundant copying, if it allows me to not worry about subtle bugs.

2024-10-26 16:12 UTC, lehins commented
Closing in favor of #504

2024-10-26 16:12 UTC, closed without merging