Align with Governance audit
IntersectMBO/cardano-base pull request #501
Opened 2024-10-01 01:04 UTC by Ranchhand87

# Description

Fixes #494, Addresses requests in #482. Please review all updates. If this is to be merged with no changes, please enable Discussions or contact @Ranchhand87 to enable.  

# Checklist

- [ Y ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ? ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages.
      **_New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-base/blob/master/RELEASING.md#changelogmd))
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/intersectmbo/cardano-base/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated.
      **_If you change the bounds in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-base/blob/master/RELEASING.md#versioning-process))
- [ Y ] Self-reviewed the diff

2024-10-24 23:26 UTC, lehins requested changes
Some of the same changes as were done for cardano-ledger are needed

2024-10-24 23:26 UTC, lehins commented on .github/ISSUE TEMPLATES/config.yml
> +    url: https://github.com/cardano-base/blob/master/CONTRIBUTING.md
```suggestion
    url: https://github.com/IntersectMBO/cardano-base/blob/master/CONTRIBUTING.md
```

2024-10-24 23:26 UTC, lehins commented on .github/ISSUE TEMPLATES/config.yml
> +    about: Check whether your issue is not already covered here.
File should end with a newline
```suggestion
    about: Check whether your issue is not already covered here.

```

2024-10-24 23:26 UTC, lehins commented on .github/ISSUE TEMPLATES/config.yml
> +
There is no need for discussions in cardano-base. Opening an issue for any reason is totally fine.
```suggestion
```

2024-10-24 23:26 UTC, lehins commented on .github/ISSUE TEMPLATES/feature_idea_base.yml
> +      required: true
I copied the template from Ledger with some adjustments
```suggestion
name: Cardano Base Repository Issue
description: Issue, Feature Enhancement, or Fix for the cardano-base repository
### Description
A clear and concise description of the problem or feature request. Include relevant context, details and the package name(s) that is affected

### Steps to Reproduce (for bugs)
1. Step 1
2. Step 2
3. Step 3
(Include screenshots if applicable)

### Expected Behavior
A clear description of what you expected to happen.

### Actual Behavior
What actually happens when following the steps. Include any error messages.

### Environment (if applicable)
- Package Name and Version:
- Operating System:
- Nix/Cabal Version:

### Additional Context
Add any other context about the problem or request here. Include possible solutions, discussions, or relevant documentation links.

### Labels
(For maintainers: add relevant labels such as `bug`, `enhancement`, `technical-debt`, etc.)
```

2024-10-24 23:26 UTC, lehins commented on CHANGELOG.md
> +- [strict-checked-vars](https://github.com/IntersectMBO/cardano-base/blob/master/strict-checked-vars/CHANGELOG.md)
This package is being removed. See #505 
```suggestion
```

2024-10-24 23:26 UTC, lehins commented on .github/ISSUE TEMPLATES/config.yml
> +    url: https://github.com/cardano-base/issues
```suggestion
    url: https://github.com/IntersectMBO/cardano-base/issues
```

2024-10-25 00:48 UTC, Ranchhand87 commented
Committed the suggestions. Apologies for any extra work, I had stepped back for a few days with other tasks, but coming back to ensure I am double and triple checking future commits. TIA

2024-10-25 18:11 UTC, lehins approved these changes
Looks great. Thank you!

2024-10-25 18:11 UTC, lehins commented on CHANGELOG.md
> +- [measures](https://github.com/IntersectMBO/cardano-base/blob/master/measures/CHANGELOG.md)
We don't allow trailing whitespaces in markdown files
```suggestion
- [base-deriving-via](https://github.com/IntersectMBO/cardano-base/blob/master/base-deriving-via/CHANGELOG.md)
- [cardano-binary](https://github.com/IntersectMBO/cardano-base/blob/master/cardano-binary/CHANGELOG.md)
- [cardano-crypto-class](https://github.com/IntersectMBO/cardano-base/blob/master/cardano-crypto-class/CHANGELOG.md)
- [cardano-crypto-praos](https://github.com/IntersectMBO/cardano-base/blob/master/cardano-crypto-praos/CHANGELOG.md)
- [cardano-crypto-tests](https://github.com/IntersectMBO/cardano-base/blob/master/cardano-crypto-tests/CHANGELOG.md)
- [cardano-mempool](https://github.com/IntersectMBO/cardano-base/blob/master/cardano-mempool/CHANGELOG.md)
- [cardano-slotting](https://github.com/IntersectMBO/cardano-base/blob/master/cardano-slotting/CHANGELOG.md)
- [cardano-strict-containers](https://github.com/IntersectMBO/cardano-base/blob/master/cardano-strict-containers/CHANGELOG.md)
- [heapwords](https://github.com/IntersectMBO/cardano-base/blob/master/heapwords/CHANGELOG.md)
- [measures](https://github.com/IntersectMBO/cardano-base/blob/master/measures/CHANGELOG.md)
```

2024-10-25 19:11 UTC, merged