Perturbing/add msm bls
IntersectMBO/cardano-base pull request #514
Opened 2024-11-26 08:25 UTC by perturbing

# Description

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] All visible changes are prepended to the latest section of a `CHANGELOG.md` for the affected packages.
      **_New section is never added with the code changes._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-base/blob/master/RELEASING.md#changelogmd))
- [ ] When applicable, versions are updated in `.cabal` and `CHANGELOG.md` files according to the
      [versioning process](https://github.com/intersectmbo/cardano-base/blob/master/RELEASING.md#versioning-process).
- [ ] The version bounds in `.cabal` files for all affected packages are updated.
      **_If you change the bounds in a cabal file, that package itself must have a version increase._** (See [RELEASING.md](https://github.com/intersectmbo/cardano-base/blob/master/RELEASING.md#versioning-process))
- [ ] Commits that only contain large amounts of formatting changes were added to `.git-blame-ignore-revs`
- [ ] Self-reviewed the diff

2024-11-26 23:32 UTC, lehins reviewed
Haven't looked into ffi calls, just at the haskell portion of it. 
I'll look into this in more depth once PR is out of draft

2024-11-27 11:12 UTC, perturbing commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +  | length ps /= length ss = Left BLST_UNKNOWN_ERROR
You are correct that the underlying blst implementation allows for it, but it just doesn't use the excess scalars. CIP-0133 [constrains](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0133#function-definition) it to be equal size.

2024-11-27 11:37 UTC, perturbing commented
Thank you for taking a first look @lehins, much appreciated!

The FFI is not working yet, I am getting some segmentation faults that I am trying to debug with valgrind.

2024-11-27 15:16 UTC, lehins commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +  | length ps /= length ss = Left BLST_UNKNOWN_ERROR
In that case the haddock is wrong

2025-01-21 14:54 UTC, perturbing commented
Hi, I fixed the bug I encountered with the memory layout (I overlooked how C code wanted the pointer).

I also added a property test, but got some weird behavior where my test's success depends on the running of other tests. See my comments [here](https://github.com/perturbing/cardano-base/blob/9bad7c5b075f6c80691bf5515257d54bd3dd991a/cardano-crypto-tests/test/Main.hs#L40) and [here](https://github.com/perturbing/cardano-base/blob/9bad7c5b075f6c80691bf5515257d54bd3dd991a/cardano-crypto-tests/src/Test/Crypto/EllipticCurve.hs#L49).

2025-01-21 21:15 UTC, lehins requested changes
I have quickly looked through the PR, but haven't spotted exactly what is wrong with this PR, but there is definitely something seriously wrong with memory management in this PR. All the non-deterministic test failures, which should not be the case with functionality that pretends to be "pure" serve as a good indicator that the functionality has a bug. Moreover, the fact that unrelated tests are affected is another strong indicator that something is seriously wrong!

I'll try to dig deeper into this functionality some time this week. Maybe I can help you get to the bottom of this.

2025-01-21 21:15 UTC, lehins commented on cardano-crypto-tests/src/Test/Crypto/EllipticCurve.hs
> +        not (null psAndSs) ==>
QuickCheck has its own [`NonEmptyList`](https://hackage.haskell.org/package/QuickCheck-2.15.0.1/docs/Test-QuickCheck-Modifiers.html#t:NonEmptyList) that can be used for generating non empty lists:
```suggestion
    , testProperty "MSM matches naive approach" $ \(NonEmpty (psAndSs :: [(BLS.Point curve, BigInteger)])) ->
```

2025-01-21 21:15 UTC, lehins commented on cardano-crypto-tests/src/Test/Crypto/EllipticCurve.hs
> +            pairs = NonEmpty.fromList (zip points scalars)
This can be easily written with list comprehensions:
```suggestion
        let pairs = NonEmpty.fromList [(p, i) | (p, BigInteger i) <- psAndSs]
```

2025-01-21 21:15 UTC, lehins commented on cardano-crypto-tests/src/Test/Crypto/EllipticCurve.hs
> +        in BLS.blsMSM pairs === foldr (\(p, s) acc -> BLS.blsAddOrDouble acc (BLS.blsMult p s)) (BLS.blsZero @curve) (zip points scalars)
`NonEmpty` is also `Foldable`, so we can just use `pairs` here:
```suggestion
        in BLS.blsMSM pairs === foldr (\(p, s) acc -> BLS.blsAddOrDouble acc (BLS.blsMult p s)) (BLS.blsZero @curve) pairs
```

2025-02-03 10:54 UTC, tdammers commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +          poke (ptr `advancePtr` ix) sPtr
Wouldn't this leak the address in `sPtr` outside the `withScalar` block?

2025-02-03 11:43 UTC, perturbing commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +          poke (ptr `advancePtr` ix) sPtr
Sharp! The same is true for the vector of pointers that is built in the `withAffineVector` function

2025-02-10 13:17 UTC, kwxm requested changes
This looks OK, but there's a problem with inputs involving the zero point which needs to be fixed.

2025-02-10 13:17 UTC, kwxm commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +              255
Could you add a comment saying what this is for, and why it's 255?  I think it corresponds to the `nbits` argument in the C code, but I'm having trouble working out what that's for.   I thought for a while that it might be the number of bits required by a scalar (in which case it would be too small), but I'm probably wrong about that.

2025-02-10 13:17 UTC, kwxm commented on cardano-crypto-tests/src/Test/Crypto/EllipticCurve.hs
> +    , testProperty "MSM matches naive approach" $ \(NonEmpty (psAndSs :: [(BLS.Point curve, BigInteger)])) ->
You might want to bias it towards including some zero points in the inputs here.

2025-02-10 13:17 UTC, kwxm commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +      sizeReference = sizeOf (undefined :: Ptr ())
I know that it doesn't get evaluated, but that `undefined` still makes me very uncomfortable.  It looks like there's no alternative though: I tried `Proxy` and GHC didn't like it.

2025-02-10 13:17 UTC, kwxm commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +    -- The accumulate function ensures that each `withAffine` call is properly nested.
I know very little about the FFI and this problem certainly wouldn't have occurred to me.  I found myself worrying about laziness though, and whether there should be some `!`s somewhere.  Does the monadic code ensure that all of this happens in the right order?

2025-02-11 08:50 UTC, perturbing commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +    let (points, scalarsAsInt) = unzipPointsAndScalars psAndSs
This is indeed something that I did not expect to happen, and glad you caught it. 

I followed the rust binding implementation, and a little [test](https://github.com/perturbing/bench-msm/blob/perturbing/test-msm-inf-point/src/main.rs) shows that it has the same behavior!

I agree that this is not something we want, as adding zero to the list of inputs would not alter the answer. I propose we use 
```Haskell
-- | Infinity check on curve points.
blsIsInf :: BLS curve => Point curve -> Bool
blsIsInf p = unsafePerformIO $ withPoint p c_blst_p_is_inf
```
To filter out pairs of points and scalars for which the point is the zero element.

2025-02-11 08:55 UTC, perturbing commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +              255
This is the size of the scalars (the order of the EC group is a 255 bit prime). I followed the rust `blstrs` implementation for these bindings, to match its use [here](https://docs.rs/blstrs/latest/src/blstrs/g1.rs.html#645) (which calls the blst rust bindings [here](https://github.com/supranational/blst/blob/165ec77634495175aefd045a48d3469af6950ea4/bindings/rust/src/lib.rs#L1615)).

2025-02-11 11:09 UTC, kwxm commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +              255
Ah, OK.  I was thinking about the size of the field elements, which definitely don't fit into 255 bits.  I wonder why the `blst` function takes this as a parameter instead of having it hard-coded or `#define`d somewhere: won't it always be 255?

2025-02-11 11:17 UTC, perturbing commented on cardano-crypto-tests/src/Test/Crypto/EllipticCurve.hs
> +    , testProperty "MSM matches naive approach" $ \(NonEmpty (psAndSs :: [(BLS.Point curve, BigInteger)])) ->
That is indeed a smart thing to do, I changed the arbitrary instance for `Point curve` in 8cd6ab6d35b51e9b7fa7b89d997b3db1b580f4bd. Note that I had to adjust the `prop_randomFailsFinalVerify` due to this change, as the former definition
```Haskell
prop_randomFailsFinalVerify :: BLS.Point1 -> BLS.Point1 -> BLS.Point2 -> BLS.Point2 -> Property
prop_randomFailsFinalVerify a b c d =
  a /= b && c /= d ==>
    BLS.ptFinalVerify (BLS.millerLoop a c) (BLS.millerLoop b d) === False
```
fails in the case where in each term, a value is `blsZero`. 

More explicitly, we have that this is true `e(a,blsZero) == e(c, blsZero)`, for which we have that `a/=b && c /= d`. In math, given `a=g^w`, `b=g^x`, `c=g^y` and `d=g^z`, for some scalars `w,x,y,z`, then by the bilinear property, we are basic testing in `e(a,c)==e(b,d)` that `w*y == x * z`. And in the case where both `c` and `d` are `blsZero = g^0`, we trivially have `w*0 == x* 0`. 

That I changed the above test to the more explicit form
```Haskell
prop_randomFailsFinalVerify :: BigInteger -> BigInteger -> BigInteger -> BigInteger -> Property
prop_randomFailsFinalVerify (BigInteger a) (BigInteger b) (BigInteger c) (BigInteger d) =
  (a * c `mod` BLS.scalarPeriod) /= (b * d `mod` BLS.scalarPeriod) ==>
    let a' = BLS.blsMult (BLS.blsGenerator @BLS.Curve1) a
        b' = BLS.blsMult (BLS.blsGenerator @BLS.Curve1) b
        c' = BLS.blsMult (BLS.blsGenerator @BLS.Curve2) c
        d' = BLS.blsMult (BLS.blsGenerator @BLS.Curve2) d
     in BLS.ptFinalVerify (BLS.millerLoop a' c') (BLS.millerLoop b' d') === False
```

2025-02-11 11:23 UTC, perturbing commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +              255
> I was thinking about the size of the field elements, which definitely don't fit into 255 bits.

The size of a field element is bound by the modulus
```Haskell
-- | The period of scalar modulo operations.
scalarPeriod :: Integer
scalarPeriod = 0x73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001
```
Note that though this is of length 32 bytes in hex notation (and thus 256 bits), it does fit in 255 bits (see [here](https://www.rapidtables.com/convert/number/hex-to-decimal.html?x=73EDA753299D7D483339D80809A1D80553BDA402FFFE5BFEFFFFFFFF00000001)).

And yes, this is constant. I am unsure why it is not.

2025-02-11 20:42 UTC, kwxm commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +              255
> The size of a field element is bound by the modulus
I think the field elements are 381 bits long, hence the name.  The 255-bit scalar period is the order of G1,G2 and GT.  I keep confusing the two!

2025-02-12 12:26 UTC, perturbing commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +              255
There two fields at play here, the base field for the curve and the scalar field. The former has elements of size 381 bits and the latter has elements of size 255 bits. 

Now for the former, we construct an elliptical curve with `x` and `y` coordinates in this base field such that `y^2 = x^3 + 4` holds. This elliptical curve forms a group, and it has a subgroup `G1` of prime order `p`. This means that it has a generator `g` and that all elements `a` of this group can be written in the form `a = g^n`. Now since this is a cyclic group, the prime order introduces a new field, which it the latter field of 255 bits.

Now the G2 and GT groups arise by making the curve equation multi dimension, they behave the same. So indeed, the prime order (`scalarPeriod` above) is also the order of these two groups :smile:

2025-05-02 11:27 UTC, perturbing reviewed
Hi, I am ready for another round of review (see also the PR description for an overview of the changes). 

Thanks in advance, much appreciated.

I think it's best to not yet merge this PR, best to first let @kwxm implement it in plutus via an SRP stanza.

2025-05-15 08:52 UTC, tdammers requested changes
Looks mostly good to me.

2025-05-15 08:52 UTC, tdammers commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +-- A pointer to a (projective) point one of the two elliptical curves
Why not make this a proper Haddock comment:
```suggestion
-- | A pointer to a (projective) point one of the two elliptical curves
```

2025-05-15 08:52 UTC, tdammers commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +withPointArray :: [Point curve] -> (PointArrayPtr curve -> IO a) -> IO a
Relying on null-termination is dangerous. Right now, usages of this function are safe, but this is brittle: the second argument to `withPointArray` there closes over the size of the original list, so it gets passed in "out of band", and implicitly depends on `withPointArray` keeping the original list length unchanged (which right now it does, but that's an implicit assumption, not part of the explicit API).

`withPointArray` as it is invites incorrect usage, so I would suggest passing the size explicitly (cf. `CString` vs. `CStringLen`):

```suggestion
withPointArray :: [Point curve] -> (Int -> PointArrayPtr curve -> IO a) -> IO a
```

2025-05-15 08:52 UTC, tdammers commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +        withPointArray points $ \pointArrayPtr -> do
See comment on `withPointArray`:
```suggestion
        withPointArray points $ \numPoints pointArrayPtr -> do
```

2025-05-15 08:52 UTC, tdammers commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +withScalarArray :: [Scalar] -> (ScalarArrayPtr -> IO a) -> IO a
See `withPointArray`:
```suggestion
withScalarArray :: [Scalar] -> (Int -> ScalarArrayPtr -> IO a) -> IO a
```

2025-05-15 08:52 UTC, tdammers commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +  -- Allocate space for the scalars and a null terminator
Why the null terminator? AFAICT, all code that consumes this API uses an explicit length to determine the end of the array; the null terminator is never used.

2025-05-15 08:52 UTC, tdammers commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +          -- will fail if the input cointaints the point at infinity.
```suggestion
          -- will fail if the input contains the point at infinity.
```

2025-05-15 08:52 UTC, tdammers commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +            else return acc
Reversing the logic will simplify this:
```suggestion
          if blsIsInf pt || scalar == zeroScalar
            then return acc
            else return ((scalar, pt) : acc)
```

2025-05-15 08:52 UTC, tdammers commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +    -- -- this case on windows builds.
```suggestion
    -- If there is only one point, we refert to blsMult function
    -- The blst_mult_pippenger C call will also not work for
    -- this case on windows builds.
```

2025-05-15 08:52 UTC, tdammers commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +-- A pointer to a null-terminated array of pointers to points
```suggestion
-- | A pointer to a null-terminated array of pointers to points
```

2025-05-15 08:52 UTC, tdammers commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +-- A pointer to an affine point on one of the two elliptical curves
```suggestion
-- | A pointer to an affine point on one of the two elliptical curves
```

2025-05-15 08:52 UTC, tdammers commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +-- A pointer to a contiguous array of affine points
```suggestion
-- | A pointer to a contiguous array of affine points
```

2025-05-15 08:52 UTC, tdammers commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +-- A pointer to a null-terminated array of pointers to affine points
```suggestion
-- | A pointer to a null-terminated array of pointers to affine points
```

2025-05-15 08:52 UTC, tdammers commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +-- | Given a block of affine points and a count, produce a null-terminated
Like `withPointArray`, I don't think this should be null-terminated.

2025-05-15 08:52 UTC, tdammers commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +          -- here we filter out pairs that will not contribute to the result
```suggestion
          -- Here we filter out pairs that will not contribute to the result.
```

2025-05-15 11:29 UTC, perturbing commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +  -- Allocate space for the scalars and a null terminator
Initially, I had it without, but the C code does use it (I discovered this by looking at the Rust implementation of the blst bindings [here](https://github.com/supranational/blst/blob/cbc7e166a10d7286b91a3a7bea341e708962db13/bindings/rust/src/pippenger.rs#L144)).

And to test it without, I ran [this](https://github.com/IntersectMBO/cardano-base/pull/514/commits/677279cc5f038ac548379d25f6fd722effe05df5) CI test, which [failed](https://github.com/IntersectMBO/cardano-base/actions/runs/14728349692/job/41336359225) on all windows machines.

2025-05-15 11:40 UTC, perturbing commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +  -- Allocate space for the scalars and a null terminator
And to add to that, there are more things that are implicit in for the blst lib that I discovered. For example, for windows builds, given one pair for an unpiut (so one point + scalar), the msm call will also fail.

And to test it, see [this](https://github.com/IntersectMBO/cardano-base/pull/514/commits/de8c2558c9c143b7b52663a949d46dac1f0fb624) and [this](https://github.com/IntersectMBO/cardano-base/actions/runs/15020090010/job/42206982810) failure on all windows tests.

2025-05-15 20:03 UTC, lehins requested changes
I had some questions and minor suggestions, but other than that it is looking good.

Needs a rebase on `master`. Also could you please add all visible changes to the Changelog and bump minor version in both cabal file and in [the latest section in the changlog file](https://github.com/IntersectMBO/cardano-base/blob/5d20803c1354d5f89cb3bc70c29f9981127bae2e/cardano-crypto-class/CHANGELOG.md?plain=1#L3) to `2.2.3.0`.

2025-05-21 08:25 UTC, perturbing commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +            else return ((scalar, pt) : acc)
Indeed, we need to modulo reduce the integer, as the mapping is not injective.

2025-05-30 22:01 UTC, lehins approved these changes
This PR looks ready to go. Thank you for the hard work @perturbing!

2025-05-30 22:05 UTC, lehins commented
@perturbing Could I ask you to cleanup the git commit history. Otherwise I am just gonna squash the whole 73 commits into one big one with very little info.

2025-05-30 22:10 UTC, perturbing commented on cardano-crypto-class/src/Cardano/Crypto/EllipticCurve/BLS12_381/Internal.hs
> +  -- Allocate space for the scalars and a null terminator
Thank you for digging into this! Ill clean up the commits after the weekend and bump the minor version + add to the changelog. Thanks for the help and the reviews!

2025-06-03 09:35 UTC, perturbing commented
I think the above is too messy, since the impact of this PR is small, I made a new PR here #536. Closing this one!

2025-06-03 09:35 UTC, closed without merging